"""One-way compatibility facade for Identity browser login."""

from app.contexts.foundations.identity.browser_login import (
    CALLBACK_PATH,
    EXCHANGE_TTL_SECONDS,
    PRODUCTION_REDIRECT_URL,
    STATE_TTL_SECONDS,
    ExternalOAuthError,
    FeishuLoginService,
    InvalidOAuthCallback,
    InvalidOAuthState,
    InvalidReturnTo,
    OAuthCompletion,
    OAuthExchangeData,
    OAuthStart,
    OAuthStateData,
    OAuthUnavailable,
    RedisOAuthStore,
    digest,
    feishu_login_service,
    get_feishu_login_service,
    get_settings,
    legacy_authorization_url,
    load_oauth_config,
    normalize_return_to,
    runtime_config,
)

__all__ = [
    "CALLBACK_PATH",
    "EXCHANGE_TTL_SECONDS",
    "ExternalOAuthError",
    "FeishuLoginService",
    "InvalidOAuthCallback",
    "InvalidOAuthState",
    "InvalidReturnTo",
    "OAuthCompletion",
    "OAuthExchangeData",
    "OAuthStart",
    "OAuthStateData",
    "OAuthUnavailable",
    "PRODUCTION_REDIRECT_URL",
    "RedisOAuthStore",
    "STATE_TTL_SECONDS",
    "digest",
    "feishu_login_service",
    "get_feishu_login_service",
    "get_settings",
    "legacy_authorization_url",
    "load_oauth_config",
    "normalize_return_to",
    "runtime_config",
]
