"""Stable Feishu browser-login facade for HTTP and lifecycle callers."""

from app.contexts.foundations.identity.infrastructure.browser_login import (
    EXCHANGE_TTL_SECONDS,
    STATE_TTL_SECONDS,
    ExternalOAuthError,
    FeishuLoginService,
    OAuthCompletion,
    OAuthExchangeData,
    OAuthStart,
    OAuthStateData,
    RedisOAuthStore,
    feishu_login_service,
    get_feishu_login_service,
    legacy_authorization_url,
)
from app.contexts.foundations.identity.infrastructure.oauth_config import (
    CALLBACK_PATH,
    InvalidOAuthCallback,
    InvalidOAuthState,
    InvalidReturnTo,
    OAuthUnavailable,
    digest,
    get_settings,
    load_oauth_config,
    normalize_return_to,
    runtime_config,
)

__all__ = [
    "CALLBACK_PATH",
    "EXCHANGE_TTL_SECONDS",
    "ExternalOAuthError",
    "FeishuLoginService",
    "InvalidOAuthCallback",
    "InvalidOAuthState",
    "InvalidReturnTo",
    "OAuthCompletion",
    "OAuthExchangeData",
    "OAuthStart",
    "OAuthStateData",
    "OAuthUnavailable",
    "RedisOAuthStore",
    "STATE_TTL_SECONDS",
    "digest",
    "feishu_login_service",
    "get_feishu_login_service",
    "get_settings",
    "legacy_authorization_url",
    "load_oauth_config",
    "normalize_return_to",
    "runtime_config",
]
